<?php

namespace SoundShare\CommunityBundle\Entity;

use Doctrine\ORM\EntityRepository;
//use SoundShare\CommunityBundle\Entity;
/**
 * MusicStyles
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MusicStylesRepository extends EntityRepository
{ 
    
}
