<?php

namespace SoundShare\CommunityBundle\Entity;

use Doctrine\ORM\EntityRepository;
//use SoundShare\CommunityBundle\Entity;
/**
 * MusicStyles
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoundFileRepository extends EntityRepository
{
    public function getPublicAndFriendSounds($userId) {
        
        $r = $this->getEntityManager()
                ->createQuery('SELECT s FROM SoundShareCommunityBundle:SoundFile s '
                        . 'WHERE (s.isPublic = 1 OR s.user IN '
                            . '(SELECT f.userId FROM  SoundShareCommunityBundle:Friends f '
                            . 'WHERE f.friendId = :uid) )')
                ->setParameter('uid', $userId)
                ->getResult();
        
        //die(dump($r));
        
        return $r;
    }
    
}
