sound_share_security_homepage:
    path:     /hello/{name}
    defaults: { _controller: SoundShareSecurityBundle:Default:index }
gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
