services: 
    shoundhsare.form.type.register:
      class: "SoundShare\\CommunityBundle\\Form\\RegisterType"      
      arguments: ["@doctrine.orm.entity_manager"]
      tags:
          - { name: form.type, alias: register }
    
    shoundhsare.form.type.music_styles:
      class: "SoundShare\\CommunityBundle\\Form\\MusicStylesType"
      #arguments: ["@doctrine.orm.entity_manager"]
      tags:
          - { name: form.type, alias: music_styles }
    
    
    soundshare.eventlistener.loginlistener:
        class : "SoundShare\\SecurityBundle\\Handler\\LoginSuccessHandler"
        arguments: ["@security.context", "@router"]
        tags:
            - {name: monolog.logger, channel: security}
            #- {name: kernel.event_listener, event: security.interactive_login, method: onAuthenticationSuccess}